# Generated by Django 4.1.6 on 2023-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="storyline",
            field=models.CharField(max_length=200),
        ),
    ]
