# Generated by Django 4.1.6 on 2023-02-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0002_alter_watchlist_storyline"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
